/*
 * Conjur
 * This is an API definition for CyberArk Conjur Open Source. You can find out more at [Conjur.org](https://www.conjur.org/).
 *
 * The version of the OpenAPI document: 5.3.0
 * Contact: conj_maintainers@cyberark.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.conjur.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * LoadedPolicy
 */
@JsonPropertyOrder({
  LoadedPolicy.JSON_PROPERTY_CREATED_ROLES,
  LoadedPolicy.JSON_PROPERTY_VERSION
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-02-05T02:00:27.403Z[GMT]")
public class LoadedPolicy {
  public static final String JSON_PROPERTY_CREATED_ROLES = "created_roles";
  private Object createdRoles;

  public static final String JSON_PROPERTY_VERSION = "version";
  private BigDecimal version;


  public LoadedPolicy createdRoles(Object createdRoles) {
    
    this.createdRoles = createdRoles;
    return this;
  }

   /**
   * Get createdRoles
   * @return createdRoles
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CREATED_ROLES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Object getCreatedRoles() {
    return createdRoles;
  }


  public void setCreatedRoles(Object createdRoles) {
    this.createdRoles = createdRoles;
  }


  public LoadedPolicy version(BigDecimal version) {
    
    this.version = version;
    return this;
  }

   /**
   * Get version
   * @return version
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getVersion() {
    return version;
  }


  public void setVersion(BigDecimal version) {
    this.version = version;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LoadedPolicy loadedPolicy = (LoadedPolicy) o;
    return Objects.equals(this.createdRoles, loadedPolicy.createdRoles) &&
        Objects.equals(this.version, loadedPolicy.version);
  }

  @Override
  public int hashCode() {
    return Objects.hash(createdRoles, version);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LoadedPolicy {\n");
    sb.append("    createdRoles: ").append(toIndentedString(createdRoles)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

