/*
 * Conjur
 * This is an API definition for CyberArk Conjur Open Source. You can find out more at [Conjur.org](https://www.conjur.org/).
 *
 * The version of the OpenAPI document: 5.3.0
 * Contact: conj_maintainers@cyberark.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.conjur.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Gets or Sets ServiceAuthenticators
 */
public enum ServiceAuthenticators {
  
  IAM("authn-iam"),
  
  OIDC("authn-oidc"),
  
  LDAP("authn-ldap"),
  
  K8S("authn-k8s"),
  
  GCP("authn-gcp"),
  
  AZURE("authn-azure"),
  
  JWT("authn-jwt");

  private String value;

  ServiceAuthenticators(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static ServiceAuthenticators fromValue(String value) {
    for (ServiceAuthenticators b : ServiceAuthenticators.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }
}

