/*
 * Conjur
 * This is an API definition for CyberArk Conjur Open Source. You can find out more at [Conjur.org](https://www.conjur.org/).
 *
 * The version of the OpenAPI document: 5.3.0
 * Contact: conj_maintainers@cyberark.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.conjur.sdk.api;

import org.conjur.sdk.model.ServiceAuthenticators;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AuthenticationApi
 */
@Ignore
public class AuthenticationApiTest {

    private final AuthenticationApi api = new AuthenticationApi();

    
    /**
     * Changes a user’s password.
     *
     * You must provide the login name and current password or API key of the user whose password is to be updated in an HTTP Basic Authentication header. Also replaces the user’s API key with a new securely generated random value. You can fetch the new API key using the Login method.  The Basic authentication-compliant header is formed by: 1. Concatenating the role&#39;s name, a literal colon character &#39;:&#39;,    and the password or API key to create the authentication string. 2. Base64-encoding the authentication string. 3. Prefixing the authentication string with the scheme: &#x60;Basic &#x60;    (note the required space). 4. Providing the result as the value of the &#x60;Authorization&#x60; HTTP header:    &#x60;Authorization: Basic &lt;authentication string&gt;&#x60;.  Your HTTP/REST client probably provides HTTP basic authentication support. For example, &#x60;curl&#x60; and all of the Conjur client libraries provide this.  Note that machine roles (Hosts) do not have passwords. They authenticate using their API keys, while passwords are only used by human users. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void changePasswordTest() {
        String account = null;
        String body = null;
        String xRequestId = null;
        api.changePassword(account, body, xRequestId);

        // TODO: test validations
    }
    
    /**
     * Enables or disables authenticator defined without service_id.
     *
     * Allows you to either enable or disable a given authenticator that does not have service_id (For example: authn-gcp).  When you enable or disable an authenticator via this endpoint, the status of the authenticator is stored in the Conjur database. The enablement status of the authenticator service may be overridden by setting the &#x60;CONJUR_AUTHENTICATORS&#x60; environment variable on the Conjur server; in the case where this environment variable is set, the database record of whether the authenticator service is enabled will be ignored.  **This endpoint is part of an early implementation of support for enabling Conjur authenticators via the API, and is currently available at the Community (or early alpha) level. This endpoint is still subject to breaking changes in the future.** 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void enableAuthenticatorTest() {
        ServiceAuthenticators authenticator = null;
        String account = null;
        String xRequestId = null;
        Boolean enabled = null;
        api.enableAuthenticator(authenticator, account, xRequestId, enabled);

        // TODO: test validations
    }
    
    /**
     * Enables or disables authenticator service instances.
     *
     * Allows you to either enable or disable a given authenticator service instance.  When you enable or disable an authenticator service instance via this endpoint, the status of the authenticator service instance is stored in the Conjur database. The enablement status of the authenticator service instance may be overridden by setting the &#x60;CONJUR_AUTHENTICATORS&#x60; environment variable on the Conjur server; in the case where this environment variable is set, the database record of whether the authenticator service instance is enabled will be ignored.  **This endpoint is part of an early implementation of support for enabling Conjur authenticators via the API, and is currently available at the Community (or early alpha) level. This endpoint is still subject to breaking changes in the future.** 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void enableAuthenticatorInstanceTest() {
        ServiceAuthenticators authenticator = null;
        String serviceId = null;
        String account = null;
        String xRequestId = null;
        Boolean enabled = null;
        api.enableAuthenticatorInstance(authenticator, serviceId, account, xRequestId, enabled);

        // TODO: test validations
    }
    
    /**
     * Gets the API key of a user given the username and password via HTTP Basic Authentication. 
     *
     * Passwords are stored in the Conjur database using &#x60;bcrypt&#x60; with a work factor of 12. Therefore, login is a fairly expensive operation. However, once the API key is obtained, it may be used to inexpensively obtain access tokens by calling the Authenticate method. An access token is required to use most other parts of the Conjur API.  The Basic authentication-compliant header is formed by: 1. Concatenating the role&#39;s name, a literal colon character &#39;:&#39;,    and the password or API key to create the authentication string. 2. Base64-encoding the authentication string. 3. Prefixing the authentication string with the scheme: &#x60;Basic &#x60;    (note the required space). 4. Providing the result as the value of the &#x60;Authorization&#x60; HTTP header:    &#x60;Authorization: Basic &lt;authentication string&gt;&#x60;.  Your HTTP/REST client probably provides HTTP basic authentication support. For example, &#x60;curl&#x60; and all of the Conjur client libraries provide this.  Note that machine roles (Hosts) do not have passwords and do not need to use this endpoint. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAPIKeyTest() {
        String account = null;
        String xRequestId = null;
        String response = api.getAPIKey(account, xRequestId);

        // TODO: test validations
    }
    
    /**
     * Gets the Conjur API key of a user given the LDAP username and password via HTTP Basic Authentication. 
     *
     * Exchange your LDAP credentials for a Conjur API key. Once the API key is obtained, it may be used to inexpensively obtain access tokens by calling the Authenticate method. An access token is required to use most other parts of the Conjur API.  The Basic authentication-compliant header is formed by: 1. Concatenating the LDAP username, a literal colon character &#39;:&#39;,    and the password to create the authentication string. 2. Base64-encoding the authentication string. 3. Prefixing the authentication string with the scheme: &#x60;Basic &#x60;    (note the required space). 4. Providing the result as the value of the &#x60;Authorization&#x60; HTTP header:    &#x60;Authorization: Basic &lt;authentication string&gt;&#x60;.  Your HTTP/REST client probably provides HTTP basic authentication support. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAPIKeyViaLDAPTest() {
        String serviceId = null;
        String account = null;
        String xRequestId = null;
        String response = api.getAPIKeyViaLDAP(serviceId, account, xRequestId);

        // TODO: test validations
    }
    
    /**
     * Gets a short-lived access token, which is required in the header of most subsequent API requests. 
     *
     * A client can obtain an access token by presenting a valid login name and API key.  The access token is used to communicate to the REST API that the bearer of the token has been authorized to access the API and perform specific actions specified by the scope that was granted during authorization.  The &#x60;login&#x60; must be URL encoded. For example, &#x60;alice@devops&#x60; must be encoded as &#x60;alice%40devops&#x60;.  The &#x60;service_id&#x60;, if given, must be URL encoded. For example, &#x60;prod/gke&#x60; must be encoded as &#x60;prod%2Fgke&#x60;.  For host authentication, the &#x60;login&#x60; is the host ID with the prefix &#x60;host/&#x60;. For example, the host webserver would login as &#x60;host/webserver&#x60;, and would be encoded as &#x60;host%2Fwebserver&#x60;.  For API usage, the base64-encoded access token is ordinarily passed as an HTTP Authorization header as &#x60;Authorization: Token token&#x3D;&lt;base64-encoded token&gt;&#x60;.  This is the default authentication endpoint only. See other endpoints for details on authenticating to Conjur using another method, e.g. for applications running in Azure or Kubernetes. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAccessTokenTest() {
        String account = null;
        String login = null;
        String body = null;
        String acceptEncoding = null;
        String xRequestId = null;
        String response = api.getAccessToken(account, login, body, acceptEncoding, xRequestId);

        // TODO: test validations
    }
    
    /**
     * Get a short-lived access token for applications running in AWS.
     *
     * The access token is used to communicate to the REST API that the bearer of the token has been authorized to access the API and perform specific actions specified by the scope that was granted during authorization.  For API usage, the base64-encoded access token is ordinarily passed as an HTTP Authorization header as &#x60;Authorization: Token token&#x3D;&lt;base64-encoded token&gt;&#x60;.  The &#x60;login&#x60; must be URL encoded and the host ID must have the prefix &#x60;host/&#x60;. For example, the host webserver would login as &#x60;host/webserver&#x60;, and would be encoded as &#x60;host%2Fwebserver&#x60;.  The &#x60;service_id&#x60;, if given, must be URL encoded. For example, &#x60;prod/gke&#x60; must be encoded as &#x60;prod%2Fgke&#x60;.  For detailed instructions on authenticating to Conjur using this endpoint, reference the documentation: [AWS IAM Authenticator](https://docs.conjur.org/Latest/en/Content/Operations/Services/AWS_IAM_Authenticator.htm) (&#x60;authn-iam&#x60;). 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAccessTokenViaAWSTest() {
        String serviceId = null;
        String account = null;
        String login = null;
        String body = null;
        String acceptEncoding = null;
        String xRequestId = null;
        String response = api.getAccessTokenViaAWS(serviceId, account, login, body, acceptEncoding, xRequestId);

        // TODO: test validations
    }
    
    /**
     * Gets a short-lived access token for applications running in Azure.
     *
     * The access token is used to communicate to the REST API that the bearer of the token has been authorized to access the API and perform specific actions specified by the scope that was granted during authorization.  For API usage, the base64-encoded access token is ordinarily passed as an HTTP Authorization header as &#x60;Authorization: Token token&#x3D;&lt;base64-encoded token&gt;&#x60;.  The &#x60;login&#x60; must be URL encoded and the host ID must have the prefix &#x60;host/&#x60;. For example, the host webserver would login as &#x60;host/webserver&#x60;, and would be encoded as &#x60;host%2Fwebserver&#x60;.  The &#x60;service_id&#x60;, if given, must be URL encoded. For example, &#x60;prod/gke&#x60; must be encoded as &#x60;prod%2Fgke&#x60;.  To authenticate to Conjur using this endpoint, reference the detailed documentation: [Azure Authenticator](https://docs.conjur.org/Latest/en/Content/Operations/Services/azure_authn.htm) (&#x60;authn-azure&#x60;). 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAccessTokenViaAzureTest() {
        String serviceId = null;
        String account = null;
        String login = null;
        String acceptEncoding = null;
        String xRequestId = null;
        String jwt = null;
        String response = api.getAccessTokenViaAzure(serviceId, account, login, acceptEncoding, xRequestId, jwt);

        // TODO: test validations
    }
    
    /**
     * Gets a short-lived access token for applications running in Google Cloud Platform. 
     *
     * Use the GCP Authenticator API to send an authentication request from a Google Cloud service to Conjur.  For more information, see [the documentation](https://docs.conjur.org/Latest/en/Content/Operations/Services/cjr-gcp-authn.htm). 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAccessTokenViaGCPTest() {
        String account = null;
        String acceptEncoding = null;
        String xRequestId = null;
        String jwt = null;
        String response = api.getAccessTokenViaGCP(account, acceptEncoding, xRequestId, jwt);

        // TODO: test validations
    }
    
    /**
     * Gets a short-lived access token for applications using JSON Web Token (JWT) to access the Conjur API. 
     *
     * Use the JWT Authenticator to leverage the identity layer provided by JWT to authenticate with Conjur. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAccessTokenViaJWTTest() {
        String account = null;
        String serviceId = null;
        String xRequestId = null;
        String jwt = null;
        String response = api.getAccessTokenViaJWT(account, serviceId, xRequestId, jwt);

        // TODO: test validations
    }
    
    /**
     * Gets a short-lived access token for applications using JSON Web Token (JWT) to access the Conjur API. Covers the case of use of optional URL parameter \&quot;ID\&quot; 
     *
     * Use the JWT Authenticator to leverage the identity layer provided by JWT to authenticate with Conjur. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAccessTokenViaJWTWithIdTest() {
        String account = null;
        String id = null;
        String serviceId = null;
        String xRequestId = null;
        String jwt = null;
        String response = api.getAccessTokenViaJWTWithId(account, id, serviceId, xRequestId, jwt);

        // TODO: test validations
    }
    
    /**
     * Gets a short-lived access token for applications running in Kubernetes.
     *
     * The access token is used to communicate to the REST API that the bearer of the token has been authorized to access the API and perform specific actions specified by the scope that was granted during authorization.  For API usage, the base64-encoded access token is ordinarily passed as an HTTP Authorization header as &#x60;Authorization: Token token&#x3D;&lt;base64-encoded token&gt;&#x60;.  The &#x60;login&#x60; must be URL encoded and the host ID must have the prefix &#x60;host/&#x60;. For example, the host webserver would login as &#x60;host/webserver&#x60;, and would be encoded as &#x60;host%2Fwebserver&#x60;.  The &#x60;service_id&#x60;, if given, must be URL encoded. For example, &#x60;prod/gke&#x60; must be encoded as &#x60;prod%2Fgke&#x60;.  To authenticate to Conjur using this endpoint, reference the detailed documentation: [Kubernetes Authenticator](https://docs.conjur.org/Latest/en/Content/Operations/Services/k8s_auth.htm) (&#x60;authn-k8s&#x60;). 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAccessTokenViaKubernetesTest() {
        String serviceId = null;
        String account = null;
        String login = null;
        String acceptEncoding = null;
        String xRequestId = null;
        String response = api.getAccessTokenViaKubernetes(serviceId, account, login, acceptEncoding, xRequestId);

        // TODO: test validations
    }
    
    /**
     * Gets a short-lived access token for users and hosts using their LDAP identity to access the Conjur API. 
     *
     * The access token is used to communicate to the REST API that the bearer of the token has been authorized to access the API and perform specific actions specified by the scope that was granted during authorization.  For API usage, the base64-encoded access token is ordinarily passed as an HTTP Authorization header as &#x60;Authorization: Token token&#x3D;&lt;base64-encoded token&gt;&#x60;.  The &#x60;login&#x60; must be URL encoded. For example, &#x60;alice@devops&#x60; must be encoded as &#x60;alice%40devops&#x60;.  The &#x60;service_id&#x60;, if given, must be URL encoded. For example, &#x60;prod/gke&#x60; must be encoded as &#x60;prod%2Fgke&#x60;.  For host authentication, the &#x60;login&#x60; is the host ID with the prefix &#x60;host/&#x60;. For example, the host webserver would login as &#x60;host/webserver&#x60;, and would be encoded as &#x60;host%2Fwebserver&#x60;.  To authenticate to Conjur using a LDAP, reference the detailed documentation: [LDAP Authenticator](https://docs.conjur.org/Latest/en/Content/Integrations/ldap/ldap_authenticator.html) (&#x60;authn-ldap&#x60;). 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAccessTokenViaLDAPTest() {
        String serviceId = null;
        String account = null;
        String login = null;
        String acceptEncoding = null;
        String xRequestId = null;
        String body = null;
        String response = api.getAccessTokenViaLDAP(serviceId, account, login, acceptEncoding, xRequestId, body);

        // TODO: test validations
    }
    
    /**
     * Gets a short-lived access token for applications using OpenID Connect (OIDC) to access the Conjur API. 
     *
     * Use the OIDC Authenticator to leverage the identity layer provided by OIDC to authenticate with Conjur.  For more information see [the documentation](https://docs.conjur.org/Latest/en/Content/OIDC/OIDC.htm). 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAccessTokenViaOIDCTest() {
        String serviceId = null;
        String account = null;
        String xRequestId = null;
        String idToken = null;
        String response = api.getAccessTokenViaOIDC(serviceId, account, xRequestId, idToken);

        // TODO: test validations
    }
    
    /**
     * For applications running in Kubernetes; sends Conjur a certificate signing request (CSR) and requests a client certificate injected into the application&#39;s Kubernetes pod. 
     *
     * This request sends a Certificate Signing Request to Conjur, which uses the Kubernetes API to inject a client certificate into the application pod.  This endpoint requires a properly configured Conjur Certificate Authority service alongside a properly configured and enabled Kubernetes authenticator. For detailed instructions, see [the documentation](https://docs.conjur.org/Latest/en/Content/Integrations/kubernetes.htm). 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void k8sInjectClientCertTest() {
        String serviceId = null;
        String body = null;
        String hostIdPrefix = null;
        String xRequestId = null;
        api.k8sInjectClientCert(serviceId, body, hostIdPrefix, xRequestId);

        // TODO: test validations
    }
    
    /**
     * Rotates a role&#39;s API key.
     *
     * Any role can rotate its own API key. The name and password (for users) or current API key (for hosts and users) of the role must be provided via HTTP Basic Authorization.  To rotate another role&#39;s API key, you may provide your name and password (for users) or current API key (for hosts and users) via HTTP Basic Authorization with the request. Alternatively, you may provide your Conjur access token via the standard Conjur &#x60;Authorization&#x60; header.  The Basic authentication-compliant header is formed by: 1. Concatenating the role&#39;s name, a literal colon character &#39;:&#39;,    and the password or API key to create the authentication string. 2. Base64-encoding the authentication string. 3. Prefixing the authentication string with the scheme: &#x60;Basic &#x60;    (note the required space). 4. Providing the result as the value of the &#x60;Authorization&#x60; HTTP header:    &#x60;Authorization: Basic &lt;authentication string&gt;&#x60;.  Your HTTP/REST client probably provides HTTP basic authentication support. For example, &#x60;curl&#x60; and all of the Conjur client libraries provide this.  If using the Conjur &#x60;Authorization&#x60; header, its value should be set to &#x60;Token token&#x3D;&lt;base64-encoded access token&gt;&#x60;.  Note that the body of the request must be the empty string. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void rotateApiKeyTest() {
        String account = null;
        String role = null;
        String xRequestId = null;
        String response = api.rotateApiKey(account, role, xRequestId);

        // TODO: test validations
    }
    
}
