/*
 * Conjur
 * This is an API definition for CyberArk Conjur Open Source. You can find out more at [Conjur.org](https://www.conjur.org/).
 *
 * The version of the OpenAPI document: 5.3.0
 * Contact: conj_maintainers@cyberark.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.conjur.sdk.api;

import org.conjur.sdk.model.LoadedPolicy;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PoliciesApi
 */
@Ignore
public class PoliciesApiTest {

    private final PoliciesApi api = new PoliciesApi();

    
    /**
     * Adds data to the existing Conjur policy.
     *
     * Adds data to the existing Conjur policy. Deletions are not allowed. Any policy objects that exist on the server but are omitted from the policy file will not be deleted and any explicit deletions in the policy file will result in an error.  ##### Permissions required  &#x60;create&#x60; privilege on the policy.\&quot; 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void loadPolicyTest() {
        String account = null;
        String identifier = null;
        String body = null;
        String xRequestId = null;
        LoadedPolicy response = api.loadPolicy(account, identifier, body, xRequestId);

        // TODO: test validations
    }
    
    /**
     * Loads or replaces a Conjur policy document.
     *
     * Loads or replaces a Conjur policy document.  **Any policy data which already exists on the server but is not explicitly specified in the new policy file will be deleted!**. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void replacePolicyTest() {
        String account = null;
        String identifier = null;
        String body = null;
        String xRequestId = null;
        LoadedPolicy response = api.replacePolicy(account, identifier, body, xRequestId);

        // TODO: test validations
    }
    
    /**
     * Modifies an existing Conjur policy.
     *
     * Modifies an existing Conjur policy. Data may be explicitly deleted using the &#x60;!delete&#x60;, &#x60;!revoke&#x60;, and &#x60;!deny&#x60; statements. Unlike &#x60;replace&#x60; mode, no data is ever implicitly deleted.  ##### Permissions required 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updatePolicyTest() {
        String account = null;
        String identifier = null;
        String body = null;
        String xRequestId = null;
        LoadedPolicy response = api.updatePolicy(account, identifier, body, xRequestId);

        // TODO: test validations
    }
    
}
