/*
 * Conjur
 * This is an API definition for CyberArk Conjur Open Source. You can find out more at [Conjur.org](https://www.conjur.org/).
 *
 * The version of the OpenAPI document: 5.3.0
 * Contact: conj_maintainers@cyberark.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.conjur.sdk.api;

import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SecretsApi
 */
@Ignore
public class SecretsApiTest {

    private final SecretsApi api = new SecretsApi();

    
    /**
     * Creates a secret value within the specified variable.
     *
     * Creates a secret value within the specified Secret.   Note: Conjur will allow you to add a secret to any resource, but the best practice is to store and retrieve secret data only using Secret resources. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createSecretTest() {
        String account = null;
        String kind = null;
        String identifier = null;
        String expirations = null;
        String xRequestId = null;
        String body = null;
        api.createSecret(account, kind, identifier, expirations, xRequestId, body);

        // TODO: test validations
    }
    
    /**
     * Fetches the value of a secret from the specified Secret.
     *
     * Fetches the value of a secret from the specified Secret. The latest version will be retrieved unless the version parameter is specified. The twenty most recent secret versions are retained.  The secret data is returned in the response body.  Note: Conjur will allow you to add a secret to any resource, but the best practice is to store and retrieve secret data only using Secret resources. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getSecretTest() {
        String account = null;
        String kind = null;
        String identifier = null;
        Integer version = null;
        String xRequestId = null;
        String response = api.getSecret(account, kind, identifier, version, xRequestId);

        // TODO: test validations
    }
    
    /**
     * Fetch multiple secrets
     *
     * Fetches multiple secret values in one invocation. It’s faster to fetch secrets in batches than to fetch them one at a time.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getSecretsTest() {
        String variableIds = null;
        String acceptEncoding = null;
        String xRequestId = null;
        Object response = api.getSecrets(variableIds, acceptEncoding, xRequestId);

        // TODO: test validations
    }
    
}
