/*
 * Conjur
 * This is an API definition for CyberArk Conjur Open Source. You can find out more at [Conjur.org](https://www.conjur.org/).
 *
 * The version of the OpenAPI document: 5.3.0
 * Contact: conj_maintainers@cyberark.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.conjur.sdk.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for AuthenticatorsResponse
 */
public class AuthenticatorsResponseTest {
    private final AuthenticatorsResponse model = new AuthenticatorsResponse();

    /**
     * Model tests for AuthenticatorsResponse
     */
    @Test
    public void testAuthenticatorsResponse() {
        // TODO: test AuthenticatorsResponse
    }

    /**
     * Test the property 'configured'
     */
    @Test
    public void configuredTest() {
        // TODO: test configured
    }

    /**
     * Test the property 'enabled'
     */
    @Test
    public void enabledTest() {
        // TODO: test enabled
    }

    /**
     * Test the property 'installed'
     */
    @Test
    public void installedTest() {
        // TODO: test installed
    }

}
