/*
 * Conjur
 * This is an API definition for CyberArk Conjur Open Source. You can find out more at [Conjur.org](https://www.conjur.org/).
 *
 * The version of the OpenAPI document: 5.3.0
 * Contact: conj_maintainers@cyberark.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.conjur.sdk.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for CreateHostTokenForm
 */
public class CreateHostTokenFormTest {
    private final CreateHostTokenForm model = new CreateHostTokenForm();

    /**
     * Model tests for CreateHostTokenForm
     */
    @Test
    public void testCreateHostTokenForm() {
        // TODO: test CreateHostTokenForm
    }

    /**
     * Test the property 'cidr'
     */
    @Test
    public void cidrTest() {
        // TODO: test cidr
    }

    /**
     * Test the property 'count'
     */
    @Test
    public void countTest() {
        // TODO: test count
    }

    /**
     * Test the property 'expiration'
     */
    @Test
    public void expirationTest() {
        // TODO: test expiration
    }

    /**
     * Test the property 'hostFactory'
     */
    @Test
    public void hostFactoryTest() {
        // TODO: test hostFactory
    }

}
