/*
 * Conjur
 * This is an API definition for CyberArk Conjur Open Source. You can find out more at [Conjur.org](https://www.conjur.org/).
 *
 * The version of the OpenAPI document: 5.3.0
 * Contact: conj_maintainers@cyberark.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.conjur.sdk.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for CsrBody
 */
public class CsrBodyTest {
    private final CsrBody model = new CsrBody();

    /**
     * Model tests for CsrBody
     */
    @Test
    public void testCsrBody() {
        // TODO: test CsrBody
    }

    /**
     * Test the property 'csr'
     */
    @Test
    public void csrTest() {
        // TODO: test csr
    }

    /**
     * Test the property 'ttl'
     */
    @Test
    public void ttlTest() {
        // TODO: test ttl
    }

}
