/*
 * Conjur
 * This is an API definition for CyberArk Conjur Open Source. You can find out more at [Conjur.org](https://www.conjur.org/).
 *
 * The version of the OpenAPI document: 5.3.0
 * Contact: conj_maintainers@cyberark.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.conjur.sdk.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ResourcePermissions
 */
public class ResourcePermissionsTest {
    private final ResourcePermissions model = new ResourcePermissions();

    /**
     * Model tests for ResourcePermissions
     */
    @Test
    public void testResourcePermissions() {
        // TODO: test ResourcePermissions
    }

    /**
     * Test the property 'policy'
     */
    @Test
    public void policyTest() {
        // TODO: test policy
    }

    /**
     * Test the property 'privilege'
     */
    @Test
    public void privilegeTest() {
        // TODO: test privilege
    }

    /**
     * Test the property 'role'
     */
    @Test
    public void roleTest() {
        // TODO: test role
    }

}
